### ISSUE TITLE
jdk15 JFX15 dependency problem

### ISSUE THREAD

**Issue by Hugolarson** [dlsc-software-consulting-gmbh/KeyboardFX#1]
I use KeybordFX with Java 8 which works fine. I just remove the mofule-info  file and build the jar.

When running with jdk15 JFX15 I get this exception. It looks like javax.xml.bind.JAXBContext is removed in JDK15.
Is this dependency really needed?

java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

**Comment by dlemmermann** [comment]
Could you comment on how you fixed this so others can benefit?

**Comment by Hugolarson** [comment]
Hi,
Wen building KeyboardFX I found dependencies to jakarta.activation-1.2.2.jar, jakarta.xml.bind-api-2.3.3.jar and jaxb-impl-2.3.3.jar in resulting keyboardfx-demo-jpro.zip.
I guess those jars are not needed when running on Java 8.
