### ISSUE TITLE
Internal library logs showing in application

### ISSUE THREAD

**Issue by Conrad6** [dlsc-software-consulting-gmbh/KeyboardFX#10]
Whenever I run my application which uses the keyboard, I keep seeing these in stdout

![image](https://user-images.githubusercontent.com/23273191/223473621-bf11bfa8-e8f2-4dc0-8ad2-4ddb193c91b5.png)

It's not breaking anything, but just thought I should point it out

**Comment by dlemmermann** [comment]
Feel free to remove and provide a PR.
