### ISSUE TITLE
FeatureRequest: Change Font Size

### ISSUE THREAD

**Issue by initialflame** [dlsc-software-consulting-gmbh/KeyboardFX#12]
Hello,

first, thank you for this great Keyboard. It is very nice and easy to use!

OnScreen-Keyboards mostly used on smaller Touchdevices. (often 10 Inch)

So it would be great to configure the Font-Size to make the Letters bigger. I think on the Keys are enough place.

Thank you!

Shawn

**Comment by dlemmermann** [comment]
Is this not something you can do via the CSS that ships with it?
