### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jrodguitar** [dlsc-software-consulting-gmbh/KeyboardFX#3]
Great work with this keyboard. It's awesome.

I wonder if for the Keyboard Pane there is a way to turn off the keyboard?
My use case is that, I can connect a physical keyboard, to my device so then i d like to add a toggle on the screen to turn on/off the keyboard on demand.

Is this possible? or will i have to fork the project and make custom modifications?

**Comment by dlemmermann** [comment]
There is no global switch anywhere. I would suggest you fork and provide a PR.

**Comment by jrodguitar** [comment]
Sounds good. Thank you.
