### ISSUE TITLE
Using it with TestFx

### ISSUE THREAD

**Issue by jrodguitar** [dlsc-software-consulting-gmbh/KeyboardFX#4]
Hello,

Thanks for the work on the keyboard.
I have created an application that is very similar to the KeyboardPaneDemoApp. And I have written TestFx tests for it, but for some reason in headless mode it doesn't work.
In headful mode things work fine.

Any ideas why in headless mode things wouldnt work at all?

As additional piece of information. I wonder if you have ever used ScenicView, to inspect the UI. When I use Scenic view, it highlights the elements yellow when you are inspecting them. But when elements are inside the KeyboardPane, it also, fails to hightlight them.

**Comment by dlemmermann** [comment]
Two tickets would have been better :-)

TestFX: I never use it so can't help you there.

ScenicView: use it all the time and also noticed that sometimes highlighting does not work. Not sure what causes it. Maybe CSS styling? You could try to completely remove the CSS file and see if it works then. If it does, keep adding CSS and see when it stops working. I know ... brute force approach ....

**Comment by dlemmermann** [comment]
Closing it as I can not help anyways. If you want to keep track of the CSS issue then please open a new ticket.
